name: Terraform Workflow

on:
  push:
    branches:
      - infra  # Change this to match your branch name
  pull_request:
    branches:
      - infra  # Change this to match your branch name

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Change this to your desired Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Plan
      run: terraform plan

    - name: Apply
      run: terraform apply -auto-approve
